trigger:
- main

resources:
- repo: self

variables:  
  IMAGE_NAME: vimalacr00005.azurecr.io/nginx-fe
  CONTAINERAPPS_APP: aca-demo-fe
  CONTAINERAPPS_ENVIRONMENT: aca-demo
  RESOURCE_GROUP: aca-demo
  TAG: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: 'Build and push image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

 

    - task: Docker@2
      displayName: 'Push image to Docker Hub'
      inputs:
        containerRegistry: 'new-acr'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        tags: '$(TAG)'

- stage: Deploy
  displayName: 'Deploy to Container Apps'
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - script: |
        echo "Debug: IMAGE_NAME = $(IMAGE_NAME)"
        echo "Debug: TAG = $(TAG)"
        echo "Debug: CONTAINERAPPS_APP = $(CONTAINERAPPS_APP)"
        echo "Debug: RESOURCE_GROUP = $(RESOURCE_GROUP)"
        echo "Debug: CONTAINERAPPS_ENVIRONMENT = $(CONTAINERAPPS_ENVIRONMENT)"
        echo "Debug: ACR_NAME = new-acr"
      displayName: 'Print Debug Information'

    - task: AzureContainerApps@1
      displayName: 'Deploy new container version'
      inputs:
        azureSubscription: 'Azure-Service-Principal'
        imageToDeploy: '$(IMAGE_NAME):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '80'
        ingress: 'external'
        acrName: 'new-acr'


