trigger:
- main

pr: none  # This prevents pull request (PR) builds, adjust as needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'
  dockerRegistryServiceConnection: 'YOUR_ACR_SERVICE_CONNECTION_NAME'  # Replace with your ACR service connection name
  imageRepository: 'vimalprasathrnginxapp'
  containerRegistry: 'nginx001.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: 'build'
    repository: '$(containerRegistry)/$(imageRepository)/$(imageName)'
    Dockerfile: '$(dockerfilePath)'
    tags: '$(tag)'

- task: Docker@2
  displayName: Push an image to ACR
  inputs:
    command: 'push'
    repository: '$(containerRegistry)/$(imageRepository)/$(imageName)'
    tags: '$(tag)'

# Add more steps or jobs as needed for your pipeline




